name: Deploy to HuggingFace Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKENG }}
        run: |
          git config --global user.email "dharnilotpal31@gmail.com"
          git config --global user.name "nilotpaldhar2004"

          git clone https://nilotpaldhar2004:${HF_TOKEN}@huggingface.co/spaces/nilotpaldhar2004/blenderbot-chatbot hf_space

          cp main.py index.html requirements.txt Dockerfile hf_space/

          cd hf_space

          git add .

          git diff --cached --quiet || git commit -m "Auto deploy from GitHub"

          git remote set-url origin https://nilotpaldhar2004:${HF_TOKEN}@huggingface.co/spaces/nilotpaldhar2004/blenderbot-chatbot

          git push origin main
